import { collection, getDocs, addDoc, Timestamp } from 'firebase/firestore';
import { db } from './firebase';

export async function seedDemoData(): Promise<void> {
  try {
    const issuesRef = collection(db, 'issues');
    const snapshot = await getDocs(issuesRef);
    console.log('Current issue count:', snapshot.size);
    
    if (snapshot.size >= 5) {
      console.log('Data exists, skipping seed');
      return;
    }
    
    console.log('Firestore empty, seeding now...');
    
    const demoIssues = [
      { trackingId: 'AP-2026-1001', title: 'Large Pothole on Anna Salai', issueCategory: 'Pothole', severityLevel: 9, priorityScore: 94, urgencyTier: 'Emergency', status: 'Reported', latitude: 13.0569, longitude: 80.2425, address: 'Anna Salai, Chennai', responsibleDepartment: 'Greater Chennai Corporation Roads Department', estimatedResolutionDays: 3, confidenceScore: 0.97, aiSummary: 'Large pothole causing traffic disruption on major arterial road.', departmentReasoning: 'GCC Roads Department responsible for arterial road maintenance.', createdByName: 'Demo User', createdBy: 'seed', imageUrl: '', letterDraft: '', letterTitle: 'Municipal Action Request' },
      { trackingId: 'AP-2026-1002', title: 'Water Leakage in T. Nagar', issueCategory: 'Water Leakage', severityLevel: 7, priorityScore: 82, urgencyTier: 'Urgent', status: 'In Progress', latitude: 13.0418, longitude: 80.2341, address: 'Usman Road, T. Nagar, Chennai', responsibleDepartment: 'Chennai Metropolitan Water Supply and Sewerage Board', estimatedResolutionDays: 5, confidenceScore: 0.91, aiSummary: 'Water pipe burst causing road flooding and water wastage.', departmentReasoning: 'CMWSSB handles water supply infrastructure repairs.', createdByName: 'Demo User', createdBy: 'seed', imageUrl: '', letterDraft: '', letterTitle: 'Municipal Action Request' },
      { trackingId: 'AP-2026-1003', title: 'Garbage Dump at Adyar Signal', issueCategory: 'Garbage Dump', severityLevel: 6, priorityScore: 71, urgencyTier: 'Important', status: 'Reported', latitude: 13.0067, longitude: 80.2576, address: 'Adyar Signal, Chennai', responsibleDepartment: 'Greater Chennai Corporation Solid Waste Management', estimatedResolutionDays: 2, confidenceScore: 0.88, aiSummary: 'Illegal garbage dump near busy junction causing health hazard.', departmentReasoning: 'GCC Solid Waste Management handles garbage collection.', createdByName: 'Demo User', createdBy: 'seed', imageUrl: '', letterDraft: '', letterTitle: 'Municipal Action Request' },
      { trackingId: 'AP-2026-1004', title: 'Broken Streetlight at Velachery', issueCategory: 'Broken Streetlight', severityLevel: 5, priorityScore: 60, urgencyTier: 'Important', status: 'Verified', latitude: 12.9815, longitude: 80.2180, address: 'Velachery Main Road, Chennai', responsibleDepartment: 'Chennai Smart City Limited Electrical Division', estimatedResolutionDays: 7, confidenceScore: 0.94, aiSummary: 'Three consecutive streetlights non-functional creating safety risk.', departmentReasoning: 'CSCL Electrical Division manages public lighting infrastructure.', createdByName: 'Demo User', createdBy: 'seed', imageUrl: '', letterDraft: '', letterTitle: 'Municipal Action Request' },
      { trackingId: 'AP-2026-1005', title: 'Drain Blockage in Mylapore', issueCategory: 'Drain Blockage', severityLevel: 8, priorityScore: 88, urgencyTier: 'Urgent', status: 'Reported', latitude: 13.0368, longitude: 80.2676, address: 'Mylapore Tank Road, Chennai', responsibleDepartment: 'Greater Chennai Corporation Drainage Division', estimatedResolutionDays: 4, confidenceScore: 0.92, aiSummary: 'Severely blocked drain causing water stagnation and flood risk.', departmentReasoning: 'GCC Drainage Division responsible for stormwater drain maintenance.', createdByName: 'Demo User', createdBy: 'seed', imageUrl: '', letterDraft: '', letterTitle: 'Municipal Action Request' },
      { trackingId: 'AP-2026-1006', title: 'Road Damage near Porur Junction', issueCategory: 'Road Damage', severityLevel: 8, priorityScore: 91, urgencyTier: 'Urgent', status: 'In Progress', latitude: 13.0358, longitude: 80.1560, address: 'Porur Junction, Chennai', responsibleDepartment: 'Greater Chennai Corporation Roads Department', estimatedResolutionDays: 6, confidenceScore: 0.96, aiSummary: 'Extensive road surface damage with alligator cracking pattern.', departmentReasoning: 'GCC Roads Department handles major road surface repairs.', createdByName: 'Demo User', createdBy: 'seed', imageUrl: '', letterDraft: '', letterTitle: 'Municipal Action Request' },
      { trackingId: 'AP-2026-1007', title: 'Water Leakage at Anna Nagar', issueCategory: 'Water Leakage', severityLevel: 6, priorityScore: 74, urgencyTier: 'Important', status: 'Resolved', latitude: 13.0891, longitude: 80.2108, address: 'Anna Nagar 2nd Avenue, Chennai', responsibleDepartment: 'Chennai Metropolitan Water Supply and Sewerage Board', estimatedResolutionDays: 5, confidenceScore: 0.89, aiSummary: 'Underground pipe leakage causing pavement damage and water loss.', departmentReasoning: 'CMWSSB manages underground water supply network.', createdByName: 'Demo User', createdBy: 'seed', imageUrl: '', letterDraft: '', letterTitle: 'Municipal Action Request' },
      { trackingId: 'AP-2026-1008', title: 'Pothole on OMR Road', issueCategory: 'Pothole', severityLevel: 7, priorityScore: 85, urgencyTier: 'Urgent', status: 'Reported', latitude: 12.9516, longitude: 80.2462, address: 'Old Mahabalipuram Road, Sholinganallur, Chennai', responsibleDepartment: 'Greater Chennai Corporation Roads Department', estimatedResolutionDays: 4, confidenceScore: 0.95, aiSummary: 'Multiple potholes on IT corridor road affecting heavy traffic.', departmentReasoning: 'GCC Roads Department responsible for OMR maintenance.', createdByName: 'Demo User', createdBy: 'seed', imageUrl: '', letterDraft: '', letterTitle: 'Municipal Action Request' },
      { trackingId: 'AP-2026-1009', title: 'Garbage Dump at Tambaram', issueCategory: 'Garbage Dump', severityLevel: 5, priorityScore: 62, urgencyTier: 'Important', status: 'Reported', latitude: 12.9249, longitude: 80.1000, address: 'Tambaram Market Road, Chennai', responsibleDepartment: 'Greater Chennai Corporation Solid Waste Management', estimatedResolutionDays: 2, confidenceScore: 0.87, aiSummary: 'Overflowing garbage bins near market area causing sanitation issues.', departmentReasoning: 'GCC Solid Waste Management handles market area sanitation.', createdByName: 'Demo User', createdBy: 'seed', imageUrl: '', letterDraft: '', letterTitle: 'Municipal Action Request' },
      { trackingId: 'AP-2026-1010', title: 'Broken Streetlight at Nungambakkam', issueCategory: 'Broken Streetlight', severityLevel: 4, priorityScore: 55, urgencyTier: 'Routine', status: 'Verified', latitude: 13.0569, longitude: 80.2425, address: 'Nungambakkam High Road, Chennai', responsibleDepartment: 'Chennai Smart City Limited Electrical Division', estimatedResolutionDays: 10, confidenceScore: 0.90, aiSummary: 'Single streetlight malfunction on residential road.', departmentReasoning: 'CSCL Electrical Division handles streetlight maintenance requests.', createdByName: 'Demo User', createdBy: 'seed', imageUrl: '', letterDraft: '', letterTitle: 'Municipal Action Request' },
      { trackingId: 'AP-2026-1011', title: 'Public Safety Hazard at Marina', issueCategory: 'Public Safety Hazard', severityLevel: 9, priorityScore: 96, urgencyTier: 'Emergency', status: 'Reported', latitude: 13.0500, longitude: 80.2824, address: 'Marina Beach Road, Chennai', responsibleDepartment: 'Greater Chennai Corporation Public Health Division', estimatedResolutionDays: 1, confidenceScore: 0.98, aiSummary: 'Exposed electrical wiring near public beach area posing electrocution risk.', departmentReasoning: 'GCC Public Health Division handles public safety emergencies.', createdByName: 'Demo User', createdBy: 'seed', imageUrl: '', letterDraft: '', letterTitle: 'Municipal Action Request' },
      { trackingId: 'AP-2026-1012', title: 'Drain Blockage at Guindy', issueCategory: 'Drain Blockage', severityLevel: 7, priorityScore: 80, urgencyTier: 'Urgent', status: 'In Progress', latitude: 13.0067, longitude: 80.2206, address: 'Guindy Industrial Estate, Chennai', responsibleDepartment: 'Greater Chennai Corporation Drainage Division', estimatedResolutionDays: 3, confidenceScore: 0.93, aiSummary: 'Industrial area drain blockage causing flooding during rain.', departmentReasoning: 'GCC Drainage Division manages industrial area stormwater systems.', createdByName: 'Demo User', createdBy: 'seed', imageUrl: '', letterDraft: '', letterTitle: 'Municipal Action Request' },
    ];

    for (const issue of demoIssues) {
      await addDoc(issuesRef, {
        ...issue,
        createdAt: Timestamp.fromDate(new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000))
      });
    }
    
    console.log('Seeded 12 demo issues successfully.');
  } catch (error) {
    console.error('Seed error:', error);
  }
}
