import React, { useState } from 'react';
import { LetterPreview } from '../components/LetterPreview';
import { ChevronLeft, Send } from 'lucide-react';
import { Issue } from '../types/Issue';
import { FullGeminiAnalysis } from '../types/GeminiAnalysis';

interface MunicipalActionRequestProps {
  analysis: FullGeminiAnalysis;
  citizenNotes: string;
  citizenName: string;
  latitude: number;
  longitude: number;
  address?: string;
  onSave: (finalIssue: Omit<Issue, 'id'>) => Promise<void>;
  onCancel: () => void;
}

export const MunicipalActionRequest: React.FC<MunicipalActionRequestProps> = ({
  analysis,
  citizenNotes,
  citizenName,
  latitude,
  longitude,
  address,
  onSave,
  onCancel
}) => {
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // Render variables
  const finalIssueData: Omit<Issue, 'id'> & { notes: string } = {
    issueId: analysis.issueId,
    imageUrl: '', // Will be updated on actual submission
    category: analysis.vision.issueCategory,
    severityLevel: analysis.vision.severityLevel,
    confidenceScore: analysis.vision.confidenceScore,
    priorityScore: analysis.priority.priorityScore,
    urgencyTier: analysis.priority.urgencyTier,
    responsibleDepartment: analysis.priority.responsibleDepartment,
    routingReason: analysis.priority.routingReason,
    estimatedResolutionDays: analysis.priority.estimatedResolutionDays,
    aiSummary: analysis.vision.aiSummary,
    latitude,
    longitude,
    address,
    createdAt: analysis.createdAt,
    status: 'Open',
    notes: citizenNotes,
    citizenName
  };

  const handleSaveReport = async () => {
    setSubmitting(true);
    setError(null);
    try {
      await onSave(finalIssueData);
    } catch (err: any) {
      console.error('Failed to submit report:', err);
      setError(err?.message || 'Failed to submit report. Please check your credentials or try again.');
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <div className="max-w-4xl w-full mx-auto px-4 py-8 z-10 relative text-left">
      
      {/* Back triggers and top dispatch control */}
      <div className="flex items-center justify-between mb-6 gap-4">
        <button
          onClick={onCancel}
          className="flex items-center gap-1.5 text-xs text-slate-400 hover:text-slate-100 font-semibold transition"
        >
          <ChevronLeft className="w-4 h-4" />
          <span>Exit Escalation Portal</span>
        </button>

        <button
          onClick={handleSaveReport}
          disabled={submitting}
          className="flex items-center gap-2 px-5 py-2.5 rounded-xl bg-emerald-500 hover:bg-emerald-400 disabled:opacity-50 disabled:cursor-not-allowed text-slate-950 font-bold text-xs uppercase tracking-wider transition-all shadow-md shadow-emerald-500/10 hover:shadow-emerald-500/20 active:scale-95"
        >
          <Send className="w-3.5 h-3.5" />
          <span>{submitting ? 'Dispatching...' : 'Dispatch Report'}</span>
        </button>
      </div>

      {/* Flagship Page Title with Technology Badges */}
      <div className="mb-6 flex flex-col md:flex-row md:items-center md:justify-between gap-4 border-b border-slate-800 pb-5">
        <div>
          <h2 className="text-2xl font-extrabold font-display text-slate-100 uppercase tracking-tight">AI-Generated Municipal Action Request</h2>
          <p className="text-xs text-slate-400 mt-1">Official high-fidelity dispatch file generated by AtlasPulse Priority Engines.</p>
        </div>
        
        {/* Google Technology Visibility Badges */}
        <div className="flex flex-wrap gap-2 items-center text-[10px] text-slate-400 font-mono bg-slate-950/60 px-3 py-1.5 rounded-xl border border-slate-800">
          <span className="px-2 py-0.5 bg-emerald-500/10 text-emerald-300 rounded border border-emerald-500/20">Powered by Gemini 2.5 Pro</span>
          <span className="px-2 py-0.5 bg-blue-500/10 text-blue-300 rounded border border-blue-500/20">Powered by Google Maps</span>
          <span className="px-2 py-0.5 bg-amber-500/10 text-amber-300 rounded border border-amber-500/20">Powered by Firebase</span>
        </div>
      </div>

      {error && (
        <div className="mb-6 text-xs text-red-400 bg-red-500/10 border border-red-500/20 p-4 rounded-2xl">
          {error}
        </div>
      )}

      <div className="w-full">
        <LetterPreview issue={finalIssueData} letterText={analysis.officialLetter} />
      </div>

      {/* High-fidelity Dispatch Confirmation Board at Bottom */}
      <div className="mt-8 bg-slate-900/60 border border-slate-800 rounded-3xl p-6 md:p-8 shadow-2xl backdrop-blur text-center max-w-2xl mx-auto">
        <div className="p-3 bg-emerald-500/10 text-emerald-400 rounded-full border border-emerald-500/20 w-fit mx-auto mb-4">
          <Send className="w-6 h-6 animate-pulse" />
        </div>
        <h3 className="text-lg font-bold font-display uppercase tracking-wider text-white mb-2">Ready for Digital Dispatch?</h3>
        <p className="text-xs text-slate-400 max-w-md mx-auto mb-6 leading-relaxed">
          Submitting will register this civic hazard into the Live Chennai Grid, assign a tracking token, and queue the official escalation brief for departmental action.
        </p>

        <div className="flex items-center justify-center gap-4">
          <button
            onClick={onCancel}
            className="px-5 py-2.5 rounded-xl bg-slate-850 hover:bg-slate-800 text-slate-300 border border-slate-700/65 font-bold text-xs uppercase tracking-wider transition"
          >
            Cancel
          </button>
          <button
            onClick={handleSaveReport}
            disabled={submitting}
            className="flex items-center gap-2 px-6 py-3 rounded-xl bg-emerald-500 hover:bg-emerald-400 disabled:opacity-50 disabled:cursor-not-allowed text-slate-950 font-bold text-sm uppercase tracking-wider transition shadow-lg shadow-emerald-500/15"
          >
            {submitting ? 'Sending Request...' : 'Confirm & Dispatch'}
          </button>
        </div>
      </div>
    </div>
  );
};
